// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type App struct {
	ID              string `json:"id"`
	Path            string `json:"path"`
	Name            string `json:"name"`
	IsDockerFile    bool   `json:"isDockerFile"`
	IsDockerCompose bool   `json:"isDockerCompose"`
}

type Env struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type Mutation struct {
}

type NewService struct {
	ServiceName       string  `json:"serviceName"`
	FromDockerCompose bool    `json:"fromDockerCompose"`
	DeployID          *string `json:"deployId,omitempty"`
	ProjectID         *string `json:"projectId,omitempty"`
}

type Project struct {
	ID       string     `json:"id"`
	Name     string     `json:"name"`
	Path     string     `json:"path"`
	Services []*Service `json:"services"`
	Apps     []*App     `json:"apps"`
}

type Query struct {
}

type Service struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Envs        []*Env   `json:"envs"`
	VolumsNames []string `json:"volumsNames"`
	Status      string   `json:"status"`
	Host        string   `json:"host"`
	DeployID    *string  `json:"deployId,omitempty"`
	ProjectID   *string  `json:"projectId,omitempty"`
	ImageName   string   `json:"imageName"`
	ImageURL    string   `json:"imageUrl"`
}
