package api

import (
	_ "cchalop1.com/deploy/docs" // docs is generated by Swag CLI, you have to import it.
	echoSwagger "github.com/swaggo/echo-swagger"
)

func CreateSwaggerRoutes(app *Application) {
	app.Echo.GET("/swagger/*", echoSwagger.WrapHandler)
}
